[package]
name = "pseudocompiler"
version = "0.1.0"
authors = ["Teymour Aldridge <teymour.aldridge@icloud.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
indextree = "4.0.0"
lazy_static = "1.4.0"
regex = "1.3.4"
wasm-bindgen = "0.2.58"