name: Build
on:
  push:
    paths:
      - "src/**"
      - "app/**"
      - "Cargo.toml"
jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build compiler
        run: wasm-pack build
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: rust-binary
          path: pkg
  build-javascript:
    needs: build-rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Download Rust binary
        uses: actions/download-artifact@v1
        with:
          name: rust-binary
          path: pkg
      - name: Install dependencies
        run: cd app && npm install && cd ../
      - name: Build
        run: cd app && npm run-script build && cd ../
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./app/build
