name: Build
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          - node-version: 12.x
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build compiler
        run: wasm-pack build
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm build
      - name: Deploy to Github pages
          uses: peaceiris/actions-gh-pages@v2.5.0
          env:
            ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: ./public
